### ISSUE TITLE
This is not an iBeracon advertisement

### ISSUE THREAD

**Issue by sloot34** [RadiusNetworks/android-ibeacon-service#14]
Hello,

When I use your library for Android and use the MacBeacon tool to generate an iBeacon, than I get the following message in my Android App "[IBeacon] This is not an iBeacon advertisment".

It looks like the iBeacon is recognized but it doesn't pass the criteria.

What's the problem?

Kindly regards,
Wouter

**Comment by davidgyoung** [comment]
Hi, Wouter.  It sounds like from the log entry that you are using an earlier version of library, perhaps 0.6.  Can you please tell me what binary version you are using (or the latest hashtag if you pulled the code from git?)

The iBeacon detection criteria was expanded in more recent copies of the software.  If you have the latest code, you won't see lines like that the the log unless you first set:

`IBeaconManager.LOG_DEBUG = true`

After you do this, if it still fails to detect your iBeacon, you should see a line like this:

`This is not an iBeacon advertisement (no 4c000215 seen in bytes 2-5).  The bytes I see are: ...`

Please try that and let me know what you see.  If you see a line like the above, please give me the exact byte sequence from the log entry.

**Comment by sloot34** [comment]
Hi David,

Thanks for your reply.
I'm using Xamarin. In this git you can see which version we're using. Perhaps you can tell me which version I use ;-)
https://github.com/chrisriesgo/xamarin-android-ibeacon-service

Looking forward to your support and reply,

Wouter

**Comment by davidgyoung** [comment]
Wouter,

It looks like the Xamarin packaged code from our respo from version 0.1
about three months ago.  There have been lots of changes since then,
including a fix to recognize a wider variety of iBeacon advertisements.
 This is why you are having trouble -- you need the latest code to solve
that problem.

Since I do not maintain that repo, I suggest you open an issue there, and
request that they re-package their jar file to include the latest code from
this library.

Thanks,
David

**Comment by davidgyoung** [comment]
Hi, @deviant-studio.

I might be able to add support if you can get multiple samples from the log for multiple Gimbal beacons.  Do you have more than one Gimbal beacon?  If so, can you try and get 10 samples for each beacon you have?

Thanks,
David

**Comment by mykola-dev** [comment]
...

upd: i think gimbal beacons not ibeacon compatible. here is what i found:
http://beekn.net/2013/12/inside-gimbal-qualcomm-beacons-tackle-bluetooth-le-challenges/
"Actually, you can’t sniff the iBeacon UUID as Gimbal use their own implementation for their beacons. They use BLE to transmit encrypted IDs that change with each broadcast, so it needs to validate with the SDK / API to confirm which beacon ID this ties up to."

**Comment by davidgyoung** [comment]
@deviant-studio, thanks for the log entries. I have added a change so these beacons can be detected.  Because the identifiers are encoded using proprietary encryption, they cannot be read, so all Gimbal beacons will show up with an all zero Proximity UUID, major and minor.  But at least they will show up!

see commit 58eed440e0176ce207b2caf416de0303e073c7f6

This will be available win the 0.7.4 binary release, probably in the next week.

**Comment by mykola-dev** [comment]
Thanks David!
I removed logs from public messages. If you need it again ill send you privately.
