### ISSUE TITLE
iBeacon count

### ISSUE THREAD

**Issue by sakitA** [RadiusNetworks/android-ibeacon-service#20]
I have two iBeacon which both of them have the same major, minor, TxPower, name, and UUID. just distance and mac address are different. but application find just one of them not both. how can I solve this problem?

**Comment by davidgyoung** [comment]
HI, Shikimaru.

The simple answer to the question is to change at least one of your identifiers on one of your iBeacons -- iBeacons are designed so the three part identifier must be unique.  The library is doing what it is supposed to do by treating these as a single iBeacon.  However, I am guessing that there is some reason you can't do this for your use case, otherwise you would have done it already.

If you really must have the library report these as two different iBeacons, then you might fork the code and modify it to use the bluetooth Mac address instead of the UUID/major/minor combo to determine a unique iBeacon.  To do this, you would have to modify the class below to (a) track the mac address, and (b) re-implement the equals method of this class to consider two iBeacons as the same only if they have the same mac address.

https://github.com/RadiusNetworks/android-ibeacon-service/blob/master/src/main/java/com/radiusnetworks/ibeacon/IBeacon.java

I am reluctant to make this change to the main library because other use cases may reasonably expect that only a single iBeacon UUID/major/minor combo could be detected at the same time, and I would not want to break existing code that expects this.

Thanks,
David

**Comment by davidgyoung** [comment]
Closing this issue.  Please reopen if you need a better solution than proposed.  Thanks, David
