### ISSUE TITLE
Single IBeaconService for multiple Apps

### ISSUE THREAD

**Issue by AaronRietschlin** [RadiusNetworks/android-ibeacon-service#22]
I am dealing with several different apps that will need to see IBeacons (for different clients). Rather than implementing different IBeaconServices for each individual app and having multiple services running at one time (which could potentially decrease battery life), is there any way that one could have a single service for all of the apps? 

I started implementing this myself, creating a custom service that implements IBeaconConsumer and will Monitor/range when necessary. I'm thinking this will require implementing some inter-process communication. Is there either: 

1.) Any way this could be done in the SDK? 
2.) Any advice you could give? 

(Looking at the source, I can see that the IBeaconService might already be setup for IPC. So, is this even something I have to worry about?)

**Comment by davidgyoung** [comment]
Hi, Aaron.

This was actually my original intention when I started building the Android
iBeaconLibrary. My thought was that if the service were already installed
by a third party app, then why start it again?  Just use the one already
installed or running.

But I quickly started running into a number of problems, specifically with
respect to security and versioning.  What if a later version of the service
has a bug fix and an older version is already running as part of a
pre-installed app.  If so, the logical thing to do is to stop that older
copy of the service and start a new one.  But that disrupts the earlier
service (at least for a brief time), thereby also disrupts the app that it
goes with.  And what if the new version of the Library introduces some
incompatibility with the previously installed app -- those app developers
never got to test with the newer library.

What's worse, what if somebody intentionally makes an trojan horse out of a
custom version of the Android iBeacon Library and installs it with their
app?  How can you know you can trust a service that is bundled with a third
party app and could be manipulated in some way?

There may be solutions to these problems, but they are complex.

The easy way to solve these problems is to have the library installed a as
a system service.  But I couldn't think of any way to do this so that the
end user wouldn't have to install two apps for their first iBeacon
application.  No novice user will be willing to do that -- they don't even
know what iBeacons are!  If Google would make it part of Core Android, then
that would be a different story.

So then I thought -- is having one copy of the service running for each app
really that bad?  The system processing is relatively minor.  The main
battery drain is in doing the bluetooth scans.  Given that only an app in
the foreground should be doing frequent bluetooth scans, there may not be a
problem at all.  And if an app does frequent bluetooth scans in the
background, then the problem is with that app specifically, regardless of
whether other apps are also using the library.

As a result, I concluded that there is no compelling reason to build a
common service at this time.  However, I am certainly open to the idea if
there is a proven performance problem with multiple service instances,
especially if there are solutions to the versioning and security problems
outlined above.

Thanks,
David

**Comment by AaronRietschlin** [comment]
Thanks for the quick response, David! I appreciate it. You bring up good points that I did not think of myself. 

"The easy way to solve these problems is to have the library installed a as
a system service."

That makes sense. This could be a completely foolish suggestion, but have you considered submitting this to AOSP? That way, the system as a whole could benefit from the beacon technology. 

Anyway, I think for now I will abandon the idea of a single service for now. Thanks again!

**Comment by davidgyoung** [comment]
Aaron, It is a surely a good idea about AOSP.  I have not gone down this
path simply because of time constraints.  If you are interested in
volunteering on the Android iBeacon Library as an open source project, that
is an area where I would love to have some help.  --David

**Comment by AaronRietschlin** [comment]
I would love to volunteer in my free-time. It would require me to do some research, but I am definitely interested. 

One last thing, sorry I forgot to mention this. You said the following:

"Given that only an app in the foreground should be doing frequent bluetooth scans, there may not be a problem at all. "

In my use case, I need to have a continually running service that listens for beacons practically at all times (able to be turned off by the user). As such, I was going to throw it into a Service with monitoring turned on, turn background mode on and forget about it. My only problem with this is it could cause severe battery drain (correct me if I am wrong). Furthermore, multiple clients are asking for similar functionality, hence my original question. So, is there something wrong with this approach?

**Comment by davidgyoung** [comment]
Check out my measurements here:

https://github.com/RadiusNetworks/android-ibeacon-service/wiki/Battery-Usage

This is a rough test, but it basically shows that constantly doing a
bluetooth scan in the background drains the battery twice as fast as if the
system were idle with cell standby being the other big battery drain.

I would _not_ do a constant scan in the background without an explicit
consent from the user, otherwise you might have an unhappy user with a dead
batter uninstalling your app.  An alternative is to use the library's
built-in background mode that slows down scans happen less frequently (30
secs every 5 min by default) to save battery.

**Comment by AaronRietschlin** [comment]
Ah, okay. Thanks for the help, David. I appreciate it.
