### ISSUE TITLE
How to get the region identifier

### ISSUE THREAD

**Issue by redamimouni** [RadiusNetworks/android-ibeacon-service#24]
Hi all,
I'm advertising an iBeacon signal using an iOS app, my beacon is like:
CLBeaconRegion *region = [super initWithProximityUUID:@"BADED00B-97BF-4E7D-9947-3425D9337FD5" major:20000 minor:50000 identifier:@"blablabla"];
My android app can only read the UUID, minor and major, is there any way to get the region identifier ("blablabla" in my case) ?

**Comment by davidgyoung** [comment]
No, you can't see that identifier on an external device because it isn't transmitted.  It is only used by iOS internally to track the CLBeacon region.   You can do something similar if you use the Pro Android iBeacon Library and access iBeacon data as described in the "Accessing iBeacon Data Example Code (Pro Library Only)" at the bottom of this page:

http://developer.radiusnetworks.com/ibeacon/android/samples.html

In this case, you would set up the iBeacon Data in the cloud using ProximityKit.com (in your example you might use a key/value of identifier=blablabla, and then you would be able to read it after the Pro Android Library detects the iBeacon.

**Comment by redamimouni** [comment]
Thank you for the answer, we try to avoid the use of cloud, its makes the exchange less instantaneous.
