### ISSUE TITLE
Nexus 7

### ISSUE THREAD

**Issue by cdsap** [RadiusNetworks/android-ibeacon-service#4]
I have the same problems with nexus7 2013 that you reported with nexus4. 
It´s possible?

**Comment by davidgyoung** [comment]
I don't have a Nexus 7 2013 edition to test with, but I do see general reports of interference between simultaneous use of bluetooth and WiFi on Google's Product forums.  See: http://productforums.google.com/forum/#!topic/nexus/ORce7P9V4qU%5B1-25-true%5D

I am kind of surprised to learn this because the Nexus 7 2013 edition is made by ASUS whereas the Nexus 4 is made by LG, but perhaps they both use the same underlying chipset as spec'd by Google.

**Comment by cdsap** [comment]
Thanks @davidgyoung , I hope with new sdk 4.4 this issue is closed.

**Comment by 2ndGAB** [comment]
Hello,
Even if the thread is closed for a long time, just to say that I'm experimenting iBeacon detection with Estimote SDK.
Everything works well on Galaxy S4 but absolutely not on Nexus 7 2013 Wifi nor LTE.
