### ISSUE TITLE
Inconsistent monitoring behavior

### ISSUE THREAD

**Issue by schickling** [RadiusNetworks/android-ibeacon-service#45]
The methods such as `didDetermineStateForRegion` of the `MonitorNotifier` aren't invoked as the iOS pendants do. In particular the following:

When I'm out of range of any beacons and I started monitoring for a region, the iOS version invokes `didDetermineStateForRegion` with state = outside. This package just invokes `didDetermineStateForRegion` if a beacon was found.

I'm not saying the behavior of this package is better or worse, I just think it would be more convenient if both systems behave the same way. I guess Apple won't change their API :smile:

**Comment by davidgyoung** [comment]
Thanks for reporting this issue.  I agree it is currently implemented as you describe, and it would be better to be consistent with the way iOS behaves.  

In order to implement this, some kind of flag would have to be kept when a region starts being monitored so its callback could be fired with state="outside" if necessary.
