### ISSUE TITLE
Mulitple Beacon monitoring problems

### ISSUE THREAD

**Issue by coomar2841** [RadiusNetworks/android-ibeacon-service#48]
I am trying to monitoring a particular region with a specific UUID, and any major/minor. So, I create a monitor with a region having my UUID, and both major and minor being null.

Now, I switch on a beacon, I get the Entry event. But after that, if I switch on another one, with the same UUID, it doesn't register an Entry event. 

Same is with Exit events as well.

Anytime after this, while the two beacons are active, and then I turn off any one of them, I don't get an Exit event. I only get an Exit event when I turn off the other active beacon also.

Is this the expected behaviour? Or I am doing something wrong?

**Comment by davidgyoung** [comment]
Coomar, this is the expected behavior.  When you set up a Region and start monitoring for it, all entry/exit events are based on the Region definition not individual beacons.  If you want to get entry/exit callbacks on a per-beacon basis,  you need to monitor for each beacon individually.

The alternative is to use the ranging APIs.
