### ISSUE TITLE
use gradle 

### ISSUE THREAD

**Issue by ligi** [RadiusNetworks/android-ibeacon-service#5]
I want to use this service for an app - part of the ground-work I just did is to gradle-I-fy all this stuff here and do some clean-up - you can find that here:

https://github.com/ligi/android-ibeacon-service
https://github.com/ligi/android-ibeacon-reference

another thing is that I released the service as a jar ( it does not have to be a library-project as it is at the moment):

https://github.com/ligi/android-ibeacon-service/releases/tag/v1.0

perhaps you want to use some of this stuff

**Comment by davidgyoung** [comment]
Thanks, this is helpful!

I have used this to create a gradle branch that does something similar.  I am keeping the project as an Android Library project as  I expect to require resources in the future.  I have therefore made a build.gradle that generates both an AndroidIBeaconLibrary.aar file for use in Gradle projects and a AndroidIBeaconLibrary.tar.gz file that can be extracted as an Eclipse Android Library project.

**Comment by ligi** [comment]
great!

I am not sure if this should be an library-project - and if it is - it should be on maven central - otherwise handling is really clumsy.
Perhaps a pure java lib as core and a library project using it to extend it with UI stuff?

**Comment by davidgyoung** [comment]
I agree about Maven.  If you'd be up for volunteering to help set that up, please contact me directly -- I'd love to have a hand!

The reason that I want to make it an aar instead of a jar is so that I can merge the service configuration from the AndroidManifest.xml to make setup easier.   I haven't done this yet, but it is on my todo list.  And I don't want to encourage people to use a jar, because it will make it impossible to inherit this configuration from the library.  I've added instructions on the project website for setting up the aar [here](http://developer.radiusnetworks.com/ibeacon/android/configure.html).

That said if _you_ want to use the jar, you can simply download the binary aar, and pull the classes.jar out of it.  Or you can build it yourself and do the same thing.

**Comment by davidgyoung** [comment]
closing this because the Gradle build has been fully implemented.  Please open a new issue about Maven if needed.
